server:
  port: 8082
  
spring:
  application:
    name: RATING-SERVICES
    
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservices 
      
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update      
        
  
eureka:
  instance:
    ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka      