server:
  port: 8085
  
  
spring:
  application:
    name: API-GATWAY 
      
  cloud:
    gateway:
      routes:
      - id: USER-SERVICES
        uri: lb://USER-SERVICES 
        predicates:
        - Path=/userServices/users/**
        
      - id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates:
        - Path=/hotelService/hotels/**
        
      - id: RATING-SERVICES
        uri: lb://RATING-SERVICES
        predicates:
        - Path=/ratingServices/ratings/**
          
#use to get common configuration from external github   
  config:
    import: optional:configserver:http://localhost:8086

#  profiles:
#    active: prod       

################################################################################################
#Bellow configuration is mention in below github repo and is fetch by  config.import property
#https://github.com/Pro456458/Microservices-Config-Server/blob/main/application.yml 
#################################################################################################    
    

#eureka:
#  instance:
#    ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
      
      