server:
  port: 8081

spring:
  application:
    name: USER-SERVICES
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update    

#use to get common configuration from external github   
  config:
    import: optional:configserver:http://localhost:8086

#  profiles:
#    active: prod       

################################################################################################
#Bellow configuration is mention in below github repo and is fetch by  config.import property
#https://github.com/Pro456458/Microservices-Config-Server/blob/main/application.yml 
#################################################################################################
     
#eureka:
#  instance:
#    ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka   